openapi: "3.0.3"
info:
  title: ToDoList API
  description: Documentação ToDoList
  version: "1.0"
servers:
  - url: http://127.0.0.1:{Port}
    description: Local
    variables:
      Port:
        default: "3000"
paths:
  # Auth
  /auth/register:
    $ref: ./paths/auth/register.yml
  /auth/login:
    $ref: ./paths/auth/login.yml

  # ToDoList
  /api/cadastrar/todo:
    $ref: ./paths/toDoList/createToDo.yml
  /api/listar/todos:
   $ref: ./paths/toDoList/listToDo.yml
  /api/editar/todos/:todo_id:
    $ref: ./paths/toDoList/patchToDo.yml
  /api/buscar/todos/:todo_id:
    $ref: ./paths/toDoList/getToDo.yml
  /api/excluir/todos/:todo_id:
    $ref: ./paths/toDoList/deleteToDo.yml